
fig = uifigure('Name', 'Temperature Adjuster', 'Position', [100 100 350 200]);

sld = uislider(fig, ...
    'Position', [75 120 200 3], ...
    'Limits', [0 100], ...
    'ValueChangedFcn', @(sld,event) updateLabel(sld));

lbl = uilabel(fig, ...
    'Position', [130 150 100 22], ...
    'Text', 'Set Temp: 0°C', ...
    'FontSize', 14);

function updateLabel(sld)
    lbl.Text = ['Set Temp: ', num2str(round(sld.Value)), '°C'];
end